### ISSUE TITLE
Nothing on display 

### ISSUE THREAD

**Issue by sajikur** [estevez-dev/ha_client_pub#20] opened 2018-09-27 18:38 UTC
After setup connection no data on screen. Simply White page

**Comment by estevez-dev** [comment] 2018-09-27 18:59
Do you have default_view configured in groups? If not - this is the case. Automatic default_view is not supported yet.

**Comment by sajikur** [comment] 2018-09-27 20:03
Thank You

In data 27 settembre 2018 20:59:24 Yegor Vialov <notifications@github.com> 
ha scritto:

**Comment by anlek** [comment] 2018-09-28 18:05
I have a similar thing happening. Not sure what a default_view config should look like, any chance there are some docs to help with this?

**Comment by My-userid** [comment] 2018-09-28 18:28
> I have a similar thing happening. Not sure what a default_view config should look like, any chance there are some docs to help with this?

https://www.home-assistant.io/components/group/

**Comment by My-userid** [comment] 2018-09-28 18:29
Same as #6

**Comment by estevez-dev** [comment] 2018-09-28 18:53
Closing as duplicate of #6 
@anlek you don't need to reconfigure your groups. I almost finished this feature and your entities will become visible after next update

**Closed by estevez-dev** 2018-09-28 18:53 UTC

**Comment by sajikur** [comment] 2018-09-29 06:08
Thank You

In data 28 settembre 2018 20:53:43 Yegor Vialov <notifications@github.com> 
ha scritto:
