### ISSUE TITLE
No title white space

### ISSUE THREAD

**Issue by klejejs** [estevez-dev/ha_client_pub#7] opened 2018-09-25 05:35 UTC
Hello!
In my HA configuration I have some cards where the title is empty because I don't want it. Currently if the title is empty the white space where the title should be is still there. Could you please make the app so that if the title == "", the place for it is hidden?
Thank you in advance and I love the app!

**Comment by estevez-dev** [comment] 2018-09-25 06:53
Nice one. Will fix in next version. Thanks!

**Comment by estevez-dev** [comment] 2018-09-25 20:10
So I tried to remove `name` from one of my group that is displayed as card. And I see group id instead of empty space. How can I reproduce it?

**Comment by klejejs** [comment] 2018-09-25 20:16
You just have to write title: ""
That worked for me.

**Comment by klejejs** [comment] 2018-09-29 11:12
![img_20180929_140956](https://user-images.githubusercontent.com/24546950/46245108-79097e00-c3f1-11e8-9b18-f95f1fe6217f.png)
Unfortunately it looks like it's still there. Maybe I am doing something wrong.
I have the latest version.

**Comment by estevez-dev** [comment] 2018-09-29 14:40
It is very strangle but I can't reproduce it. Could you please past here exact config for this group?

**Comment by klejejs** [comment] 2018-09-29 16:53
Here you go! Really hope it helps.
![image](https://user-images.githubusercontent.com/24546950/46248381-44151f80-c421-11e8-8785-9096f7ca24a7.png)

**Comment by estevez-dev** [comment] 2018-09-29 17:31
Oh, it is not empty, it is "space" symbol =)
If you want an empty title, just make it empty, not space.
How this group looks in Home Assistant web ui?

**Comment by klejejs** [comment] 2018-09-29 18:28
Thank you! :)

**Comment by estevez-dev** [comment] 2018-10-01 08:52
Fixed in 0.2.1

**Closed by estevez-dev** 2018-10-01 08:52 UTC
Labels: area: ui, internal issue linked
