### ISSUE TITLE
nothing on the front appears

### ISSUE THREAD

**Issue by dnerds** [estevez-dev/ha_client_pub#19] opened 2018-09-27 06:18 UTC
[Debug] :  AppLifecycleState.resumed
[Debug] :  Socket connecting...
[Debug] :  [Sending] ==> auth request
[Debug] :  Settings change event: reconnect=true
[Debug] :  Socket connecting...
[Debug] :  [Sending] ==> auth request
[Debug] :  [Sending] ==> {"id": 1, "type": "subscribe_events", "event_type": "state_changed"}
[Debug] :  [Sending] ==> {"id": 2, "type": "get_config"}
[Debug] :  [Sending] ==> {"id": 3, "type": "get_states"}
[Debug] :  Parsing 40 Home Assistant entities
[Debug] :  Gethering views
[Debug] :  [Sending] ==> {"id": 4, "type": "get_services"}
[Debug] :  Parsing 13 Home Assistant service domains
[Debug] :  AppLifecycleState.inactive
[Debug] :  AppLifecycleState.paused
[Error] :  No new_state found
[Error] :  No new_state found
[Error] :  No new_state found
[Debug] :  AppLifecycleState.inactive
[Debug] :  AppLifecycleState.resumed
[Debug] :  [Sending] ==> {"id": 5, "type": "get_config"}
[Debug] :  [Sending] ==> {"id": 6, "type": "get_states"}
[Debug] :  Parsing 37 Home Assistant entities
[Debug] :  Gethering views
[Debug] :  [Sending] ==> {"id": 7, "type": "get_services"}
[Debug] :  Parsing 13 Home Assistant service domains
[Debug] :  AppLifecycleState.inactive
[Debug] :  AppLifecycleState.paused
[Debug] :  AppLifecycleState.inactive
[Debug] :  AppLifecycleState.resumed
[Debug] :  [Sending] ==> {"id": 8, "type": "get_config"}
[Debug] :  [Sending] ==> {"id": 9, "type": "get_states"}
[Debug] :  Parsing 37 Home Assistant entities
[Debug] :  Gethering views
[Debug] :  [Sending] ==> {"id": 10, "type": "get_services"}
[Debug] :  Parsing 13 Home Assistant service domains

**Comment by My-userid** [comment] 2018-09-27 07:40
I have the same problem.
It seems to login fine, but nothing is showing, just the blue top and the rest is white.

Samsung Galaxy S8.

**Comment by estevez-dev** [comment] 2018-09-27 09:59
Thanks for reports guys. I will close this as duplicate of #6 . Please subscribe to issue #6 for updates.

**Closed by estevez-dev** 2018-09-27 09:59 UTC
