### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED SSL error with Let's Encrypt cert

### ISSUE THREAD

**Issue by jaimievansanten** [estevez-dev/ha_client_pub#13] opened 2018-09-25 21:46 UTC
Hi,

I'm getting the following error when I try to use the app. Visiting HA over browser reports no issues. I did have to supply `verify=false` to custom python scripts (running on same machine as HA) in order to get them to connect.

```
[Debug] :  AppLifecycleState.inactive
[Debug] :  AppLifecycleState.resumed
[Debug] :  Socket connecting...
[Global error] :  WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:363))
```

**Comment by estevez-dev** [comment] 2018-09-26 06:39
Known issue. Closing as duplicate of #3

**Closed by estevez-dev** 2018-09-26 06:39 UTC
